name: Pull Salesforce Metadata

on:
  push:
    branches:
    - nkn-boss-patch-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Salesforce CLI
      run: npm install sfdx-cli --global
    
    - name: Authenticate with Salesforce using JWT Token
      run: sfdx force:auth:jwt:grant --clientid 3MVG9pe2TCoA1Pf7qdc9Ay2ASNktlwe.tZrmEb_yA5NhOnI_ubtjHlX4O9vVB4Fr.SkCdg2RMrv2TrniBsnfx --jwtkeyfile server.key --username nkn@tambolalwc.com --instanceurl https://test.salesforce.com --setalias my-org-alias

    - name: Retrieve metadata
      run: sfdx force:source:retrieve -u my-org-alias -r force-app -x package.xml

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions@example.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Retrieved metadata from Salesforce"
        git push
